CREATE TABLE USERGUILDMESSAGE (
    USER_ID INT,
    GUILD_ID INT,
    MESSAGE_ID INT,
    PRIMARY KEY (USER_ID, GUILD_ID, MESSAGE_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID),
    FOREIGN KEY (GUILD_ID) REFERENCES GUILD (GUILD_ID),
    FOREIGN KEY (MESSAGE_ID) REFERENCES MESSAGE (MESSAGE_ID)
);
