CREATE TABLE GUILDUSER (
    GUILD_ID INT,
    USER_ID INT,
    PRIMARY KEY (GUILD_ID, USER_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID),
    FOREIGN KEY (GUILD_ID) REFERENCES GUILD (GUILD_ID)
);